name: golf_diary_flutter
description: A Golf Diary app with multi-language support
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  printing: ^5.14.2
  pdf: ^3.10.4
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  fl_chart: ^0.69.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/GolfDiarySans.ttf
    - assets/fonts/NotoSansSC-Regular.otf
    - assets/images/golf_background.png
    - assets/images/game_background.png
    - assets/icon/chopstick_icon.png
    - assets/icon/compass_icon.png
    - assets/courses_new.json

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/golfdiary.png"
